Approach 3: github-action-matrix-outputs-write/read
Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -122,6 +122,9 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
+    - name: Debug - fail if on macos
+      if: "matrix.os == 'macos-latest'"
+      run: exit 1
     - name: Display initial Python packages
       run: |
         echo "Installed Python packages:"
@@ -206,12 +209,36 @@ jobs:
         PACKAGE_LEVEL: ${{ matrix.package_level }}
       run: |
         make safety
+    - name: Debug - Print job.status
+      if: "!cancelled()"
+      run: echo "${{ job.status }}"
+    - name: Write test job status
+      if: "!cancelled()"
+      uses: hoverkraft-tech/ci-github-common/actions/set-matrix-output@main
+      with:
+        value: "${{ job.status }}"
+        artifact-name: test_status
 
   test_finish:
     needs: test
+    if: "!cancelled()"
+    # Note: By default, failures of dependent jobs cause this job to be
+    # cancelled which counts as a success. The above condition causes this job
+    # to run regardless of dependent jobs status, except if the workflow was
+    # cancelled.
     runs-on: ubuntu-latest
     container: python:3-slim
     steps:
+    - name: Read test job status
+      id: read_status
+      uses: hoverkraft-tech/ci-github-common/actions/get-matrix-outputs@main
+      with:
+        artifact-name: test_status
+    - name: Debug - Print steps.read_status.outputs
+      run: echo "${{ steps.read_status.outputs }}"
+    - name: Fail if any test job failed
+      if: "contains('false', steps.read_status.outputs.status)"
+      run: exit 1
     - name: Install coveralls
       run: |
         pip3 install --upgrade coveralls
